### ISSUE TITLE
配置文件不存在,请检查环境: open /service/config/config.ini: The system cannot find the path specified.

### ISSUE THREAD

**Issue by ouzexi** [suanju/Go-Live-Service#11]

**Comment by suanju** [comment]
需要修改路径哦

**Comment by ouzexi** [comment]
你好，请问提示 ffmpeg 状态异常请检查后重试 该如何解决，感谢！

**Comment by suanju** [comment]
下载ffmpeg 配置环境变量

**Comment by ouzexi** [comment]
你好，我已经下载了的，我在cmd输入ffmpeg -version是正常打印的，但是启动后端就会报这个错误了。

**Comment by ouzexi** [comment]
看了下日志，打印报错信息："open livego.yaml: The system cannot find the file specified."

**Comment by ouzexi** [comment]
"handleConn HandshakeServer err: EOF"

**Comment by suanju** [comment]
你这是启动livego 时候错误

**Comment by suanju** [comment]
建议使用docker

**Comment by ouzexi** [comment]
好的，感谢您的回答！
