### ISSUE TITLE
upload video error

### ISSUE THREAD

**Issue by JcccKing** [suanju/Go-Live-Service#7]
![image](https://user-images.githubusercontent.com/46700363/235096563-fe837e5a-59bd-4894-9f62-555bef7439eb.png)
您好这是为什么 后续在拼接 视频对象的时候 会出现nil
![image](https://user-images.githubusercontent.com/46700363/235097085-5353a08c-95bb-4c94-83b5-e8669c57eaae.png)

**Comment by suanju** [comment]
这个是因为我考虑我服务器性能获取视频时长在前端做的，前端获取视频时长失败了，后续可能考虑更新
